# Generated by Django 3.0.8 on 2020-08-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200807_1253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Listing',
        ),
    ]
