# Generated by Django 3.0.8 on 2020-08-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200807_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Closedlisting',
            field=models.CharField(default='Listing has been closed', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='Category',
            field=models.CharField(choices=[('Memes', 'Memes'), ('Processors', 'Processors'), ('Gpus', 'GPUS'), ('RAM', 'Ram'), ('Monitor', 'Monitor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Description',
            field=models.TextField(),
        ),
    ]
