# Generated by Django 3.0.8 on 2020-08-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200808_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Closedlisting',
            field=models.CharField(max_length=23),
        ),
    ]
